# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ManageSystem' do

pod 'AFNetworking'
pod 'SVProgressHUD', '~> 1.1.3'

end

target 'ManageSystemTests' do

end

