# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ManageSystem' do

pod 'AFNetworking'
pod 'SVProgressHUD', '~> 1.1.3'
pod 'MJRefresh', '~> 2.4.11'
pod 'DZNEmptyDataSet', '~> 1.7.2'

end

target 'ManageSystemTests' do

end

